using JLD2
using HTTP
using JSON3
using Dates
using Printf
using Random
using UUIDs
using LinearAlgebra

# ─── Parameters (edit these) ─────────────────────────────────────────────────
const K        = 10    # number of goods
const L        = 5     # memory length: periods of history given to pricing LLMs
const N_TYPES  = 4     # number of consumer types to use (1–4, from TYPE_NAMES below)
const SIGMA    = 1.0   # std dev of Normal noise added to each consumer's a vector
const N_AGENTS = 500   # number of consumers per period
const T_PERIODS = 50   # number of simulation ticks

# All 2^K binary baskets, precomputed once (1024 for K=10)
const ALL_BASKETS = [[(mask >> (k-1)) & 1 for k in 1:K] for mask in 0:(2^K - 1)]

# ─── Shopper types ───────────────────────────────────────────────────────────
const TYPE_NAMES = ["breakfast", "pantry", "coffee", "balanced"]

const TYPE_MEANS = Dict(
    "breakfast" => Float64[8, 8, 7, 5, 8, 7, 4, 2, 3, 2],
    "pantry"    => Float64[3, 2, 6, 5, 4, 3, 2, 1, 8, 8],
    "coffee"    => Float64[5, 3, 4, 2, 3, 2, 8, 7, 2, 2],
    "balanced"  => Float64[6, 5, 6, 4, 6, 4, 5, 3, 5, 5],
)

const TYPE_PROBS = Float64[0.30, 0.25, 0.15, 0.30]  # must sum to 1

# Mean shopping budget per type (integer dollars); noise set by BUDGET_SIGMA
const TYPE_BUDGETS = Dict(
    "breakfast" => 25,
    "pantry"    => 30,
    "coffee"    => 15,
    "balanced"  => 20,
)
const BUDGET_SIGMA = 5.0   # std dev of Normal noise on budget before rounding

# ─── Pricing strategy abstraction ────────────────────────────────────────────
# Concrete subtypes are generated by the LLM and appended to strategies.jl.
# Each subtype defines:
#   get_prices(s::Strategy_N) → Vector{Rational{Int}}
#   feasible(s::Strategy_N, budget::Int64, consumer::Consumer, bundle::Bundle)
#             → (max_net_utility::Float64, best_basket::Vector{Int})
abstract type PricingStrategy end

# ─── Bundle ───────────────────────────────────────────────────────────────────
# The Bundle holds every piece of the environment generated by the LLM.
# Saving it to JLD2 makes the simulation exactly reproducible.
# Costs are stored as Rational{Int} so that profit arithmetic stays exact.
struct Bundle
    goods::Vector{String}              # length K
    costs::Vector{Rational{Int}}       # unit cost per good, length K (same for both stores)
    B::Matrix{Float64}                 # K x K interaction matrix
    sign_matrix::Matrix{String}        # K x K, entries "C" / "S" / "0"
    rationale::Vector{String}          # explanation for each nonzero off-diagonal pair
    raw_llm_response::String           # full LLM JSON response, for auditing
end

# ─── Consumer ─────────────────────────────────────────────────────────────────
struct Consumer
    type::String           # shopper type label
    a::Vector{Float64}     # standalone utility weights, length K
    budget::Int            # maximum total spend at a store (integer dollars)
    preferred_store::Int   # 0=none, 1=store1, 2=store2
end

# Generate N_AGENTS consumers by drawing types, adding utility noise, and
# drawing an integer budget from a type-specific Normal distribution.
# TYPE_PROBS[1:N_TYPES] is renormalised so N_TYPES can be set freely.
function generate_consumers(rng::AbstractRNG = Random.default_rng();
                            loyal_share::Float64=0.0)::Vector{Consumer}
    probs = TYPE_PROBS[1:N_TYPES]
    probs = probs ./ sum(probs)
    cdf   = cumsum(probs)

    consumers = Vector{Consumer}(undef, N_AGENTS)
    for i in 1:N_AGENTS
        r = rand(rng)
        t = findfirst(p -> r <= p, cdf)
        t = t === nothing ? N_TYPES : t
        type = TYPE_NAMES[t]

        a      = max.(TYPE_MEANS[type] .+ randn(rng, K) .* SIGMA, 0.0)
        budget = max(1, round(Int, TYPE_BUDGETS[type] + randn(rng) * BUDGET_SIGMA))

        r2 = rand(rng)
        preferred_store = r2 < loyal_share / 2 ? 1 :
                          r2 < loyal_share      ? 2 : 0

        consumers[i] = Consumer(type, a, budget, preferred_store)
    end
    return consumers
end

# ─── Store agent ─────────────────────────────────────────────────────────────
# Stores are initialised here; pricing is set by LLM calls each period.
# Prices and financials are Rational{Int} for exact arithmetic.
mutable struct Store
    id::Int
    price_history::Vector{Vector{Rational{Int}}}    # prices posted each period, length K each
    revenue_history::Vector{Rational{Int}}           # gross revenue each period
    cost_history::Vector{Rational{Int}}              # total cost of goods sold each period
    profit_history::Vector{Rational{Int}}            # profit = revenue − cost each period
    strategy_names::Vector{String}                   # name of strategy used each period
    rationale_history::Vector{String}                # LLM's explanation of each strategy
end

init_store(id::Int) = Store(id,
    Vector{Rational{Int}}[], Rational{Int}[], Rational{Int}[], Rational{Int}[],
    String[], String[])

# ─── Revenue / cost / profit ──────────────────────────────────────────────────
# baskets: one Vector{Int} per consumer who chose this store that period.
# All arithmetic stays exact (Rational{Int}) until display.

function store_revenue(s::PricingStrategy, baskets::Vector{Vector{Int}})::Rational{Int}
    isempty(baskets) && return zero(Rational{Int})
    prices = Base.invokelatest(get_prices, s)
    return sum(dot(prices, b) for b in baskets)
end

function store_cost(bundle::Bundle, baskets::Vector{Vector{Int}})::Rational{Int}
    isempty(baskets) && return zero(Rational{Int})
    return sum(dot(bundle.costs, b) for b in baskets)
end

function store_profit(s::PricingStrategy, bundle::Bundle,
                      baskets::Vector{Vector{Int}})::Rational{Int}
    return store_revenue(s, baskets) - store_cost(bundle, baskets)
end

# ─── Strategy generation ──────────────────────────────────────────────────────
const STRATEGIES_FILE = "strategies.jl"

# Unique 8-hex-char prefix for this run — prevents struct name collisions
# when strategies.jl is reloaded across multiple runs.
# Format: Strategy_A3F7B2C1_1, Strategy_A3F7B2C1_2, ...
const RUN_ID = uppercase(replace(string(uuid4())[1:8], "-" => ""))

function next_strategy_number()::Int
    isfile(STRATEGIES_FILE) || return 1
    return count("struct Strategy_", read(STRATEGIES_FILE, String)) + 1
end

# Canonical struct name for a strategy given its sequence number.
strategy_name(n::Int) = "Strategy_$(RUN_ID)_$(n)"

# Own-store context: prices + profits (last L ticks).
function fmt_history_own(store::Store, bundle::Bundle, lookback::Int=L)::String
    T = length(store.profit_history)
    T == 0 && return "  (no history yet)"
    lines = String[]
    for t in max(1, T - lookback + 1):T
        p = store.price_history[t]
        price_str = join([@sprintf("%s=%.2f", bundle.goods[k], Float64(p[k]))
                          for k in 1:length(bundle.goods)], ", ")
        push!(lines, "  tick $t: prices=[$price_str]  profit=$(Float64(store.profit_history[t]))")
    end
    return join(lines, "\n")
end

# Opponent context: prices ONLY — profits are not observable by the other store.
function fmt_history_opp(store::Store, bundle::Bundle, lookback::Int=L)::String
    T = length(store.price_history)
    T == 0 && return "  (no history yet)"
    lines = String[]
    for t in max(1, T - lookback + 1):T
        p = store.price_history[t]
        price_str = join([@sprintf("%s=%.2f", bundle.goods[k], Float64(p[k]))
                          for k in 1:length(bundle.goods)], ", ")
        push!(lines, "  tick $t: prices=[$price_str]")
    end
    return join(lines, "\n")
end

# Call the LLM to generate a new pricing strategy, append it to strategies.jl,
# load it into the running session, and return the instantiated strategy object.
function generate_strategy(api_key::String, store_id::Int, tick::Int,
                            bundle::Bundle,
                            own_store::Store, opp_store::Store;
                            no_loss_constraint::Bool=false,
                            seek_nash::Bool=false,
                            collusion::Bool=false,
                            threats::Bool=false,
                            lookback::Int=L)::Tuple{PricingStrategy, String}
    N    = next_strategy_number()
    sname = strategy_name(N)

    goods_str = join(["  $k. $(bundle.goods[k])  (wholesale cost: $(bundle.costs[k]))"
                      for k in 1:length(bundle.goods)], "\n")
    cost_str  = join(["$(bundle.goods[k])=$(bundle.costs[k])"
                      for k in 1:length(bundle.goods)], ", ")

    loss_constraint_str = no_loss_constraint ? """
CONSTRAINT: Do not sustain negative profits for more than 1–2 consecutive periods. \
If your recent history shows repeated losses, you must raise prices to return to \
profitability. Brief loss-leading on individual goods is acceptable, but persistent \
store-level losses are not.
""" : ""

    nash_str = seek_nash ? """
OBJECTIVE: You are playing a non-cooperative game. Try to find a Nash equilibrium — \
a price vector such that, given your competitor's prices, you have no incentive to \
deviate unilaterally. You cannot communicate or coordinate with your competitor; \
you must infer their likely strategy from observed price history and best-respond \
accordingly. The Nash equilibrium in a Bertrand market is prices equal to marginal \
cost, but with heterogeneous consumers and multiple goods the equilibrium may differ.
""" : ""

    collusion_str = collusion ? """
OBJECTIVE: You and your competitor are acting as a cartel. Your shared goal is to \
maximise combined profit across both stores. Set prices as high as the market will \
bear. Treat the competitor's prices as coordinated with yours — if they price high, \
you should too. Do not undercut; hold the line on prices to sustain joint profits.
""" : ""

    threats_str = (collusion && threats) ? """
ENFORCEMENT: You may use punishment threats to deter deviation. If your competitor \
undercuts the collusive price, you should immediately revert to aggressive competitive \
pricing on all goods for the remainder of the game (grim trigger). State this threat \
explicitly in your rationale so the competitor can observe it in future periods. \
Conversely, if you have been threatened, take it seriously and do not deviate.
""" : ""

    prompt = """
You are the strategic pricing agent for Store $store_id in a repeated \
competitive grocery game (current tick: $tick).
Your goal is to maximise your store's cumulative profit over time.
$loss_constraint_str$nash_str$collusion_str$threats_str
GOODS AND WHOLESALE COSTS:
$goods_str

YOUR HISTORY (last $lookback ticks) — your prices and your profit:
$(fmt_history_own(own_store, bundle, lookback))

COMPETITOR'S PRICING (last $lookback ticks) — prices only, their profit is not observable:
$(fmt_history_opp(opp_store, bundle, lookback))

Return a JSON object with exactly two fields:

1. "rationale": 2–4 sentences in plain English explaining your pricing decision.
   Describe what strategy you are pursuing, why you chose it given the history,
   and what outcome you expect. Write in first person as the store's pricing agent.

2. "prices": an array of exactly $(length(bundle.goods)) positive numbers (floats),
   one retail price per good, in the same order as the goods list above.
   You may price any good below its wholesale cost (loss leaders allowed).
   Wholesale costs for reference: $cost_str
"""

    body = JSON3.write(Dict(
        "model"           => "gpt-4o",
        "response_format" => Dict("type" => "json_object"),
        "messages"        => [
            Dict("role" => "system",
                 "content" => "You are a strategic pricing agent. Return only a JSON object with keys \"rationale\" (string) and \"prices\" (array of numbers)."),
            Dict("role" => "user", "content" => prompt),
        ],
        "temperature" => 0.7,
    ))

    response = HTTP.post(
        "https://api.openai.com/v1/chat/completions",
        ["Authorization" => "Bearer $api_key", "Content-Type" => "application/json"],
        body,
    )

    result    = JSON3.read(String(response.body))
    parsed    = JSON3.read(String(result.choices[1].message.content))
    rationale = String(parsed["rationale"])

    # Parse prices from the JSON array
    prices_raw = [Float64(p) for p in parsed["prices"]]
    length(prices_raw) == length(bundle.goods) ||
        error("LLM returned $(length(prices_raw)) prices, expected $(length(bundle.goods))")

    # Ensure all prices are strictly positive, then rationalise
    prices_raw = max.(prices_raw, 0.01)
    prices_rat = [rationalize(Int, p, tol=0.005) for p in prices_raw]
    prices_str = join(["$(numerator(p))//$(denominator(p))" for p in prices_rat], ", ")

    # Generate the Julia code ourselves — no LLM code generation, no parse errors
    code = """
struct $sname <: PricingStrategy
    number::Int
    tick_created::Int
end

get_prices(s::$sname) = Rational{Int}[$prices_str]

function feasible(s::$sname, budget::Int64, consumer::Consumer, bundle::Bundle)
    prices = get_prices(s)
    best_u = -Inf
    best_x = zeros(Int, length(bundle.goods))
    for x in ALL_BASKETS
        if dot(prices, x) ≤ budget
            u = dot(consumer.a, x) + 0.5 * (x' * bundle.B * x) - dot(prices, x)
            if u > best_u
                best_u = u
                best_x = copy(x)
            end
        end
    end
    return best_u, best_x
end
"""

    # Append to strategies.jl with rationale as comments
    open(STRATEGIES_FILE, "a") do f
        println(f, "\n# ── $sname | Store $store_id | tick $tick ──────────────────────────────")
        for line in split(rationale, "\n")
            println(f, "# $line")
        end
        print(f, code)
        println(f)
    end

    # Load only this new block into the running session
    include_string(Main, code)

    strategy_type = getfield(Main, Symbol(sname))
    return Base.invokelatest(strategy_type, N, tick), rationale
end

# ─── LLM call: generate full environment bundle ───────────────────────────────
function generate_bundle(api_key::String)::Bundle
    prompt = """
You are designing the environment for a grocery store competition simulation.

The simulation has K=$K goods. Use exactly these goods (in this order):
milk, cereal, bread, butter, eggs, bacon, coffee, sugar, pasta, pasta_sauce

Return a single JSON object with exactly these five fields:

1. "goods": array of $K strings (snake_case names, same order as above).

2. "costs": array of $K numbers giving a plausible wholesale unit cost in USD
   for each good (e.g. milk ≈ 1.50, coffee ≈ 5.00). These represent the cost
   paid by the store per unit sold, the same for both stores.

3. "B_matrix": a $(K)x$(K) array of arrays of floats.
   This is the interaction matrix in the consumer utility model:
       U(x) = a'x + 0.5 * x'Bx,   x ∈ {0,1}^K
   Rules:
   - Diagonal must be 0.
   - Must be exactly symmetric: B[i][j] == B[j][i].
   - Keep sparse: most entries should be 0.
   - Use only: +2.0 (strong complement), +1.0 (moderate complement),
               -0.5 (weak substitute), -1.0 (moderate substitute), 0.0 (none).
   - Apply grocery intuition:
       milk & cereal → strong complement
       bread & butter → strong complement
       eggs & bacon → strong complement
       coffee & sugar → moderate complement
       pasta & pasta_sauce → strong complement

4. "sign_matrix": a $(K)x$(K) array of arrays of strings.
   Each entry is "C" (complement), "S" (substitute), or "0" (no interaction).
   Must be consistent with B_matrix and symmetric.

5. "rationale": array of strings, one per nonzero off-diagonal pair
   (upper triangle only), formatted as "good_i - good_j: reason".
"""

    body = JSON3.write(Dict(
        "model"           => "gpt-4o",
        "response_format" => Dict("type" => "json_object"),
        "messages"        => [
            Dict("role" => "system",
                 "content" => "You are a precise assistant that returns only valid JSON."),
            Dict("role" => "user", "content" => prompt),
        ],
        "temperature" => 0.2,
    ))

    response = HTTP.post(
        "https://api.openai.com/v1/chat/completions",
        ["Authorization" => "Bearer $api_key", "Content-Type" => "application/json"],
        body,
    )

    raw = String(response.body)
    result  = JSON3.read(raw)
    content = String(result.choices[1].message.content)
    parsed  = JSON3.read(content)

    # goods
    goods = String[String(g) for g in parsed["goods"]]
    length(goods) == K || error("LLM returned $(length(goods)) goods, expected $K")

    # costs — rationalise to nearest cent so arithmetic stays exact
    costs = Rational{Int}[rationalize(Int, Float64(c), tol=0.005) for c in parsed["costs"]]
    length(costs) == K || error("LLM returned $(length(costs)) costs, expected $K")

    # B matrix
    B = Matrix{Float64}(undef, K, K)
    for i in 1:K, j in 1:K
        B[i, j] = Float64(parsed["B_matrix"][i][j])
    end
    B = (B + B') / 2          # enforce symmetry
    for i in 1:K; B[i,i] = 0.0; end  # enforce zero diagonal

    # sign matrix
    sign_matrix = Matrix{String}(undef, K, K)
    for i in 1:K, j in 1:K
        sign_matrix[i, j] = String(parsed["sign_matrix"][i][j])
    end

    rationale = String[String(r) for r in parsed["rationale"]]

    return Bundle(goods, costs, B, sign_matrix, rationale, content)
end

# ─── Main simulation loop ─────────────────────────────────────────────────────
function run_simulation(api_key::String, bundle::Bundle,
                        consumers::Vector{Consumer},
                        store1::Store, store2::Store;
                        utility_noise_sigma::Float64=0.0,
                        loyalty_bump::Float64=0.0)

    println("\n═══ Simulation start: $T_PERIODS ticks, $N_AGENTS consumers ══════════════")

    # Initial strategies generated with empty history
    println("\nGenerating initial strategies (tick 0)...")
    strategy1, rat1 = generate_strategy(api_key, 1, 0, bundle, store1, store2)
    strategy2, rat2 = generate_strategy(api_key, 2, 0, bundle, store2, store1)
    println("  Store 1: $(typeof(strategy1))\n    \"$rat1\"")
    println("  Store 2: $(typeof(strategy2))\n    \"$rat2\"")

    for tick in 1:T_PERIODS
        println("\n─── Tick $tick / $T_PERIODS " * "─"^40)

        # ── Consumer choice ───────────────────────────────────────────────────
        baskets1 = Vector{Int}[]   # baskets of consumers who chose store 1
        baskets2 = Vector{Int}[]   # baskets of consumers who chose store 2

        for consumer in consumers
            u1, b1 = Base.invokelatest(feasible, strategy1, consumer.budget, consumer, bundle)
            u2, b2 = Base.invokelatest(feasible, strategy2, consumer.budget, consumer, bundle)
            e1 = utility_noise_sigma > 0.0 ? randn() * utility_noise_sigma : 0.0
            e2 = utility_noise_sigma > 0.0 ? randn() * utility_noise_sigma : 0.0
            loy1 = consumer.preferred_store == 1 ? loyalty_bump : 0.0
            loy2 = consumer.preferred_store == 2 ? loyalty_bump : 0.0
            if (u1 + e1 + loy1) >= (u2 + e2 + loy2)
                push!(baskets1, b1)
            else
                push!(baskets2, b2)
            end
        end

        # ── Financials ────────────────────────────────────────────────────────
        rev1    = store_revenue(strategy1, baskets1)
        cost1   = store_cost(bundle, baskets1)
        profit1 = rev1 - cost1

        rev2    = store_revenue(strategy2, baskets2)
        cost2   = store_cost(bundle, baskets2)
        profit2 = rev2 - cost2

        # ── Record history ────────────────────────────────────────────────────
        push!(store1.price_history,    Base.invokelatest(get_prices, strategy1))
        push!(store1.revenue_history,  rev1)
        push!(store1.cost_history,     cost1)
        push!(store1.profit_history,   profit1)
        push!(store1.strategy_names,   string(typeof(strategy1)))
        push!(store1.rationale_history, rat1)

        push!(store2.price_history,    Base.invokelatest(get_prices, strategy2))
        push!(store2.revenue_history,  rev2)
        push!(store2.cost_history,     cost2)
        push!(store2.profit_history,   profit2)
        push!(store2.strategy_names,   string(typeof(strategy2)))
        push!(store2.rationale_history, rat2)

        # ── Tick summary ──────────────────────────────────────────────────────
        n1, n2 = length(baskets1), length(baskets2)
        println(@sprintf("  Customers → store 1: %4d  store 2: %4d", n1, n2))
        println(@sprintf("  Store 1 — revenue: %7.2f  cost: %7.2f  profit: %+7.2f",
                         Float64(rev1), Float64(cost1), Float64(profit1)))
        println(@sprintf("  Store 2 — revenue: %7.2f  cost: %7.2f  profit: %+7.2f",
                         Float64(rev2), Float64(cost2), Float64(profit2)))

        # ── Generate next strategies (not needed after final tick) ────────────
        if tick < T_PERIODS
            println("  Generating strategies for tick $(tick + 1)...")
            strategy1, rat1 = generate_strategy(api_key, 1, tick, bundle, store1, store2)
            strategy2, rat2 = generate_strategy(api_key, 2, tick, bundle, store2, store1)
            println("    Store 1: \"$rat1\"")
            println("    Store 2: \"$rat2\"")
        end
    end

    println("\n═══ Simulation complete ══════════════════════════════════════════")
end

# ─── JLD2 helpers ────────────────────────────────────────────────────────────
function save_bundle(filename::String, bundle::Bundle)
    @save filename bundle
    println("Bundle saved to: $filename")
end

function load_bundle(filename::String)::Bundle
    local bundle::Bundle
    @load filename bundle
    println("Bundle loaded from: $filename")
    return bundle
end

# ─── Display helpers ─────────────────────────────────────────────────────────
function col_label(g::String)
    lpad(g[1:min(5, length(g))], 7)
end

function row_label(g::String)
    lpad(g[1:min(12, length(g))], 14)
end

function print_sign_matrix(bundle::Bundle)
    println(lpad("", 14) * join(col_label.(bundle.goods)))
    for i in 1:K
        row = row_label(bundle.goods[i])
        for j in 1:K
            row *= lpad(bundle.sign_matrix[i, j], 7)
        end
        println(row)
    end
end

function print_B_matrix(bundle::Bundle)
    println(lpad("", 14) * join(col_label.(bundle.goods)))
    for i in 1:K
        row = row_label(bundle.goods[i])
        for j in 1:K
            v = bundle.B[i, j]
            row *= lpad(v == 0.0 ? "·" : string(v), 7)
        end
        println(row)
    end
end

function print_bundle_summary(bundle::Bundle)
    println("\n─── Goods and costs ──────────────────────────────────────────")
    println(lpad("good", 16) * lpad("cost (\$)", 12) * lpad("(rational)", 14))
    for i in 1:K
        c = bundle.costs[i]
        println(
            lpad(bundle.goods[i], 16) *
            lpad(@sprintf("%.4f", Float64(c)), 12) *
            lpad("$(numerator(c))//$(denominator(c))", 14)
        )
    end

    println("\n─── Sign matrix ──────────────────────────────────────────────")
    print_sign_matrix(bundle)

    println("\n─── Numeric B matrix ─────────────────────────────────────────")
    print_B_matrix(bundle)

    println("\n─── Rationale ────────────────────────────────────────────────")
    for r in bundle.rationale
        println("  • $r")
    end
end

function print_store_narrative(store::Store)
    T = length(store.profit_history)
    println("\n" * "═"^70)
    println("  Store $(store.id) — Strategic Narrative")
    println("═"^70)
    for t in 1:T
        profit_str = @sprintf("%+.2f", Float64(store.profit_history[t]))
        println("\n  Tick $t  │  profit: $profit_str  │  $(store.strategy_names[t])")
        for line in split(store.rationale_history[t], ". ")
            line = strip(line)
            isempty(line) && continue
            println("    " * line * (endswith(line, ".") ? "" : "."))
        end
    end
    println("\n" * "═"^70)
end

function print_store(store::Store)
    T = length(store.profit_history)
    println("\n─── Store $(store.id) ────────────────────────────────────────────────")
    if T == 0
        println("  No periods played yet. Pricing set by LLM each period.")
    else
        println(lpad("period", 8) * lpad("revenue", 12) * lpad("cost", 12) * lpad("profit", 12))
        for t in 1:T
            println(
                lpad(t, 8) *
                lpad(@sprintf("%.2f", Float64(store.revenue_history[t])), 12) *
                lpad(@sprintf("%.2f", Float64(store.cost_history[t])),    12) *
                lpad(@sprintf("%+.2f", Float64(store.profit_history[t])), 12)
            )
        end
    end
end

# ─── Main ─────────────────────────────────────────────────────────────────────
function main()
    if length(ARGS) < 1
        println(stderr, "Usage: julia competition.jl <openai_api_key> [setup_file.jld2]")
        exit(1)
    end

    api_key    = ARGS[1]
    setup_file = length(ARGS) >= 2 ? ARGS[2] : nothing

    # ── Reload any previously generated strategies ────────────────────────────
    if isfile(STRATEGIES_FILE)
        println("Loading existing strategies from $STRATEGIES_FILE ...")
        include(STRATEGIES_FILE)
    end

    # ── Load or generate bundle ───────────────────────────────────────────────
    bundle = if setup_file !== nothing && isfile(setup_file)
        load_bundle(setup_file)
    else
        println("Calling LLM to generate environment bundle...")
        b = generate_bundle(api_key)
        fname = setup_file !== nothing ? setup_file :
                "setup_" * Dates.format(now(), "yyyymmdd_HHMMSS") * ".jld2"
        save_bundle(fname, b)
        b
    end

    # ── Initialise stores ─────────────────────────────────────────────────────
    store1 = init_store(1)
    store2 = init_store(2)

    # ── Generate consumer population ──────────────────────────────────────────
    consumers = generate_consumers()
    type_counts = Dict(t => count(c -> c.type == t, consumers) for t in TYPE_NAMES[1:N_TYPES])

    # ── Print summary ─────────────────────────────────────────────────────────
    println("\n─── Simulation parameters ───────────────────────────────────")
    println("  K (goods)           = $K")
    println("  L (memory periods)  = $L")
    println("  N_TYPES             = $N_TYPES")
    println("  SIGMA (util. noise) = $SIGMA")
    println("  N_AGENTS            = $N_AGENTS")

    println("\n─── Consumer population ──────────────────────────────────────")
    println(lpad("type", 14) * lpad("n", 8) * lpad("budget μ", 12) * lpad("budget σ", 12))
    for t in TYPE_NAMES[1:N_TYPES]
        budgets = [c.budget for c in consumers if c.type == t]
        println(
            lpad(t, 14) *
            lpad(length(budgets), 8) *
            lpad(@sprintf("%.1f", sum(budgets) / length(budgets)), 12) *
            lpad(@sprintf("%.1f", sqrt(sum((b - sum(budgets)/length(budgets))^2
                          for b in budgets) / length(budgets))), 12)
        )
    end

    print_bundle_summary(bundle)
    print_store(store1)
    print_store(store2)

    # ── Run simulation ────────────────────────────────────────────────────────
    run_simulation(api_key, bundle, consumers, store1, store2)

    # ── Final store summaries and narratives ──────────────────────────────────
    print_store(store1)
    print_store(store2)
    print_store_narrative(store1)
    print_store_narrative(store2)
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
